channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # - mamba # Having difficulties installing the newest version of mamba
    # - aria2
    # - assembly-stats
    # - binutils
    # - biopython
    # - curl
    # - extern
    # - git
    # - htop
    # - hck
    # - jupyterlab
    # - nbconvert
    # - ipython
    # - newick_utils
    # # when listed, openssh somehow forces R to version < 4, which causes havoc.
    # # Instead I just install openssh to its own env and add it to the path
    # # - openssh>=9.3p1
    # - pandoc
    # - sqlite
    # - tar
    # - tqdm
    # - xsv
    # - zstd
    # - ncbi-acc-download
    # # - tmux==3.3a
    # - gh
    # - r-svglite
    # - r-lubridate
    # # - jq # Fails to resolve with the other deps, so just have a binary in ~/bin
    # - r-bit64
    # - yapf
    # - r-languageserver
    # - r-ggpubr
    # - shap
    # - joblib
    # - pyarrow
    # - xgboost
    # - plotnine
    # - bird_tool_utils_python
    # # r-stringi 1.7.6 fails because the wrong library is linked
    # - r-stringi >= 1.7.12
    # - ripgrep
    # - psutil
    # - sed
  - jupyter # required for vscode?
  - python
  - r>=4.2
  - r-ggplot2
  - r-data.table
  - r-irkernel
  - parallel
  - polars
  - pandas
  - scikit-learn
