# This file is autogenerate by ensembl_species_id_prefixes_autogenerator.rb - DO NOT MODIFY DIRECTLY!
module Bio
  class Ensembl
    # Auto-generated 2011-07-23 for Ensembl version 63
    ENSEMBL_SPECIES_HASH = 
    {
    'ENSMIC' => ['gray mouse lemur','microcebus_murinus'],
    'ENSNLE' => ['Northern white-cheeked gibbon','nomascus_leucogenys'],
    'ENSMGA' => ['domestic turkey','meleagris_gallopavo'],
    'ENSDOR' => ['Ords kangaroo rat','dipodomys_ordii'],
    'ENSOPR' => ['American pika','ochotona_princeps'],
    'ENSVPA' => ['alpaca','vicugna_pacos'],
    'ENSLAF' => ['African savanna elephant','loxodonta_africana'],
    'ENSXET' => ['western clawed frog','xenopus_tropicalis'],
    'ENSOAN' => ['platypus','ornithorhynchus_anatinus'],
    'ENSGAL' => ['chicken','gallus_gallus'],
    'ENSTTR' => ['bottlenosed dolphin','tursiops_truncatus'],
    'ENSMEU' => ['tammar wallaby','macropus_eugenii'],
    'ENSCAF' => ['dog','canis_familiaris'],
    'ENSCIN' => ['Sea squirt Ciona intestinalis','ciona_intestinalis'],
    'ENSRNO' => ['Norway rat','rattus_norvegicus'],
    'ENSGAC' => ['three-spined stickleback','gasterosteus_aculeatus'],
    'ENSORL' => ['Japanese medaka','oryzias_latipes'],
    'ENSOGA' => ['small-eared galago','otolemur_garnettii'],
    'ENSACA' => ['green anole','anolis_carolinensis'],
    'ENSEEU' => ['western European hedgehog','erinaceus_europaeus'],
    'ENSMMU' => ['rhesus monkey','macaca_mulatta'],
    'ENSCHO' => ['Hoffmanns two-fingered sloth','choloepus_hoffmanni'],
    'ENSDAR' => ['zebrafish','danio_rerio'],
    'ENSETE' => ['small Madagascar hedgehog','echinops_telfairi'],
    'ENSMUS' => ['house mouse','mus_musculus'],
    'ENSMLU' => ['little brown bat','myotis_lucifugus'],
    'ENSOCU' => ['rabbit','oryctolagus_cuniculus'],
    'ENSTGU' => ['zebra finch','taeniopygia_guttata'],
    'ENSCPO' => ['domestic guinea pig','cavia_porcellus'],
    'ENSMOD' => ['gray short-tailed opossum','monodelphis_domestica'],
    'FB' => ['fruit fly','drosophila_melanogaster'],
    'ENSTRU' => ['torafugu','takifugu_rubripes'],
    'ENSTBE' => ['northern tree shrew','tupaia_belangeri'],
    'ENSECA' => ['horse','equus_caballus'],
    'ENSSSC' => ['pig','sus_scrofa'],
    'ENSCSAV' => ['Sea squirt Ciona savignyi','ciona_savignyi'],
    'ENSPCA' => ['cape rock hyrax','procavia_capensis'],
    'ENSSTO' => ['thirteen-lined ground squirrel','spermophilus_tridecemlineatus'],
    'ENSSAR' => ['European shrew','sorex_araneus'],
    'ENSFCA' => ['domestic cat','felis_catus'],
    'ENSAME' => ['giant panda','ailuropoda_melanoleuca'],
    'ENSPTR' => ['chimpanzee','pan_troglodytes'],
    'ENSPPY' => ['Bornean orangutan','pongo_abelii'],
    'ENSTNI' => ['spotted green pufferfish','tetraodon_nigroviridis'],
    'ENSCJA' => ['white-tufted-ear marmoset','callithrix_jacchus'],
    'ENSDNO' => ['nine-banded armadillo','dasypus_novemcinctus'],
    'ENSGGO' => ['Western Gorilla','gorilla_gorilla'],
    'ENSBTA' => ['cattle','bos_taurus'],
    'ENSTSY' => ['Philippine tarsier','tarsius_syrichta'],
    'ENS' => ['human','homo_sapiens'],
    'ENSPVA' => ['large flying fox','pteropus_vampyrus'],
    }
  end
end

