#!/usr/bin/env ruby

require 'tempfile'
require 'optparse'

# Parse cmd line options
USAGE = "Usage: trees_distance [-r <repetitions>] [-d <directory>] <fasta_multiple_sequence_alignment>"
options = {
  :repetitions => 1000,
  :directory => 'trees_parsimony'
}
OptionParser.new do |opts|
  opts.banner = USAGE

  opts.on("-r", "--repetitions [REPETITIONS]", Integer, "Number of bootstrap repetitions to do") do |v|
    options[:repetitions] = v
  end
  
  opts.on('-d', '--directory DIRECTORY', String, "Directory of the working and output files") do |v|
    options[:directory] = v
  end
end.parse!
p options
bootstrapping = (options[:repetitions] != 1)

if ARGV.length != 1
  $stderr.puts USAGE
  exit
end
fasta_file_input = ARGV[0]

Dir.mkdir options[:directory]
system("sreformat phylip #{fasta_file_input} >#{options[:directory]}/ununiqued.phylip")
Dir.chdir options[:directory]
system('uniqify_phylip.rb <ununiqued.phylip >uniqued.phylip')

# Do the boostrapping
if bootstrapping
  system('ln -s uniqued.phylip infile')
  Tempfile.open('trees_parsimony.seqboot.params') do |tempfile|
    tempfile.puts 'R'
    tempfile.puts options[:repetitions] #1000 by default
    tempfile.puts 'Y'
    tempfile.puts '73'
    tempfile.close

    system("phylip seqboot <#{tempfile.path}")
  end
  system('mv outfile seqboot.outfile')
  system('rm infile')

  # prepare for parsimony tree creation
  system('ln -s seqboot.outfile infile')
else
  # prepare for parsimony tree creation
  system('ln -s uniqued.phylip infile')
end

# create parsimony trees
Tempfile.open('trees_parsimony.protpars.params') do |tempfile|
  if bootstrapping
    tempfile.puts 'M'
    tempfile.puts 'D'
    tempfile.puts options[:repetitions] #1000 by default
  end
  #  tempfile.puts '1'
  #  tempfile.puts '2' # Turn of indications because it wastes disk space and I think causes it to fail as well.
  #  tempfile.puts '3' # Turn of tree writing to outfile because that isn't needed and wastes disk space
  tempfile.puts 'Y'
  tempfile.puts '79'
  tempfile.close

  system("phylip protpars <#{tempfile.path}")
end
system('mv outfile protpars.outfile')
system('mv outtree protpars.outtree')
system('rm infile')

# Make the consensus tree
system('ln -s protpars.outtree intree')
Tempfile.open('trees_parsimony.consense.params') do |tempfile|
  tempfile.puts 'y'
  tempfile.close
  system("phylip consense <#{tempfile.path}")
end
system('mv outfile consense.outfile')
system('mv outtree consense.outtree')
system('rm intree')

#convert the names on the tree back to sensible land
Dir.chdir '..'
system("ununiqify_standard_tree.rb #{fasta_file_input} #{options[:directory]}/uniqued.phylip #{options[:directory]}/consense.outtree >#{options[:directory]}/parsimony.tree")
