#!/usr/bin/env ruby

require 'tempfile'
require 'optparse'

# Parse cmd line options
USAGE = "Usage: trees_distance [-r <repetitions>] <fasta_multiple_sequence_alignment>"
options = {
  :repetitions => 1000
}
OptionParser.new do |opts|
  opts.banner = USAGE
  
  opts.on("-r", "--repetitions [REPETITIONS]", Integer, "Number of bootstrap repetitions to do") do |v|
    options[:repetitions] = v
  end
end.parse!
p options

if ARGV.length != 1
  $stderr.puts USAGE
  exit
end
fasta_file_input = ARGV[0]

system('mkdir trees_distance') or raise
system("sreformat phylip #{fasta_file_input} >trees_distance/ununiqued.phylip")
Dir.chdir('trees_distance')
system('uniqify_phylip.rb <ununiqued.phylip >uniqued.phylip')

# Do the boostrapping
system('ln -s uniqued.phylip infile')
Tempfile.open('trees_distance.seqboot.params') do |tempfile|
  tempfile.puts 'R'
  tempfile.puts options[:repetitions] #1000 by default
  tempfile.puts 'Y'
  tempfile.puts '73'
  tempfile.close #required. Maybe because it doesn't flush otherwise?
  
  system("phylip seqboot <#{tempfile.path}") or raise Exception, $?.inspect
end
system('mv outfile seqboot.outfile') or raise Exception, $?.inspect
system('rm infile') or raise Exception, $?.inspect

# create distance tree
puts "Running protdist"
system('ln -s seqboot.outfile infile')
Tempfile.open('trees_distance.protdist.params') do |tempfile|
  tempfile.puts 'M'
  tempfile.puts 'D'
  tempfile.puts options[:repetitions] #1000 by default
  tempfile.puts 'Y'
  tempfile.close #required. Maybe because it doesn't flush otherwise?
  
  system("phylip protdist <#{tempfile.path}")
end
system('mv outfile protdist.outfile')
system('rm infile')

# do a bionj tree
Tempfile.open('trees_distance.bionj.params') do |tempfile|
  tempfile.puts 'protdist.outfile'
  tempfile.puts 'bionj.outfile'
  tempfile.close #required. Maybe because it doesn't flush otherwise?
  
  system("bionj <#{tempfile.path}") or raise Exception, $?
end

# Make the consensus tree
system('ln -s bionj.outfile intree')
Tempfile.open('trees_distance.consense.params') do |tempfile|
  tempfile.puts 'y'
  tempfile.close
  system("phylip consense <#{tempfile.path}")
end
system('mv outfile consense.outfile')
system('mv outtree consense.outtree')
system('rm intree')

#convert the names on the tree back to sensible land
Dir.chdir('..')
system("ununiqify_standard_tree.rb #{fasta_file_input} trees_distance/uniqued.phylip trees_distance/consense.outtree >trees_distance/distance.tree")
