# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 

$:.unshift File.join(File.dirname(__FILE__),'..','lib')

require 'rubygems'
require 'test/unit'
require 'trimpoly'
require 'construct'
include Bio

class TrimpolyTest < Test::Unit::TestCase
  include Construct::Helpers
  
  def test_trim_both
    # test killing the whole sequence
    sequence = 'GCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTXXXXXXXXXXXXXXXXXXXXACTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_both(sequence)
    assert_nil trimmed
    
    # test killing part of the sequence
    sequence = 'XXXXXXXXXXXXXTCGATTXXXXXXXXXXXXXXXXXXXXXXACAATTCGACGTCATCTACTAAGGTAGTTTTCGACGGATCCGTCTATATTCTGACGACTTTGACATCCCTTGTAACAGACATGGXXXXXXXXXXTCTAACGGCGACAAGGTTCTTCTCAGCAGTATCGGCTCTGTGGTCCGCCTCCTCGATCAGCTGCTGAGCTTTGCGGTACTTTTTTTTTTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_both(sequence)
    assert_equal 'XXXXXXXXXXXXXTCGATTXXXXXXXXXXXXXXXXXXXXXXACAATTCGACGTCATCTACTAAGGTAGTTTTCGACGGATCCGTCTATATTCTGACGACTTTGACATCCCTTGTAACAGACATGGXXXXXXXXXXTCTAACGGCGACAAGGTTCTTCTCAGCAGTATCGGCTCTGTGGTCCGCCTCCTCGATCAGCTGCTGAGCTTTGCGGTAC', 
      trimmed
    
    # test do nothing
    sequence = 'AGGACTCTTCTGAAGACCACGTGACCCTCTGATACGGCTGAAAATATTTGATCTTCTACATTGTAATATTCTTTCAAGTGCAATATTAGTTATTTAAACTTTTATATGTTATAAAGATTCATTGTGATATTTATTGAAAATGTGAGAAAAAGAAACAATTAAATATTTTTTCTCAGGATATCGTTTCAGAATAATGCGGAGATTTCTAAAGAATAACGTTAATTCGATTGGACTGTTAAGCTCTTGTXXX'  
    trimmed = Trimpoly.trim_both(sequence)
    assert_equal sequence, trimmed
  end

  def test_trim_poly_a_only
    sequence = 'GCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTXXXXXXXXXXXXXXXXXXXXACTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_poly_a(sequence)
    assert_equal sequence, trimmed

    sequence = 'CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCTaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaattaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAA'
    trimmed = Trimpoly.trim_poly_a(sequence)
    assert_equal 'CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCT',
      trimmed
  end

  def test_trim_poly_t_only
    # test yes
    sequence = 'GCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTXXXXXXXXXXXXXXXXXXXXACTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_poly_t(sequence)
    assert_equal nil, trimmed

    # test polyA -> shouldn't result in anything
    sequence = 'CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCTaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaattaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAA'
    trimmed = Trimpoly.trim_poly_t(sequence)
    assert_equal sequence, trimmed
  end

  def test_script
    input = '>1|test
CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCTaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaattaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAA
>2|test
TCTCACGGGGCGCGGCAGGTGGGGGGGCAGCCTCCCCATGTGTTGCCCCGGGACAGCAGCTACATGGGCACCATGATTGACGATCTGGTGAGCAAGGACCTGCGGGAGCCCTATCGGGTCCTCACCAGTCGCAGTGAATATCGGCTCCTGCTGCGGGGCGATAACGCTGATCGACGGCTCACACCCATGGGCCGGGAGTTGGGTCTGGTGGATGATCGCCGCTGGCGCACCTTCGAGGCCAAGCAAAAGGCCATCCAGGCCCAGCAAGCCCTGTTGGAGACCACCCGCCTCAAGGCCGATGACCCGGTTAG'

    # Assumes trimpoly.rb is in the path
    within_construct do |construct|
      construct.directory 'alice/rabbithole' do |dir|
        dir.file 'white_rabbit.fa', input
        system 'trimpoly.rb white_rabbit.fa >white_rabbit.trimpoly.fa'
        assert_equal '>1|test
CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCT
>2|test
TCTCACGGGGCGCGGCAGGTGGGGGGGCAGCCTCCCCATGTGTTGCCCCGGGACAGCAGCTACATGGGCACCATGATTGACGATCTGGTGAGCAAGGACCTGCGGGAGCCCTATCGGGTCCTCACCAGTCGCAGTGAATATCGGCTCCTGCTGCGGGGCGATAACGCTGATCGACGGCTCACACCCATGGGCCGGGAGTTGGGTCTGGTGGATGATCGCCGCTGGCGCACCTTCGAGGCCAAGCAAAAGGCCATCCAGGCCCAGCAAGCCCTGTTGGAGACCACCCGCCTCAAGGCCGATGACCCGGTTAG
',
          File.read('white_rabbit.trimpoly.fa')
      end
    end

    within_construct do |construct|
      construct.directory 'alice/rabbithole' do |dir|
        dir.file 'white_rabbit.fa', input
        system 'trimpoly.rb -A white_rabbit.fa >white_rabbit.trimpoly.fa'
        assert_equal '>1|test
CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCT
>2|test
TCTCACGGGGCGCGGCAGGTGGGGGGGCAGCCTCCCCATGTGTTGCCCCGGGACAGCAGCTACATGGGCACCATGATTGACGATCTGGTGAGCAAGGACCTGCGGGAGCCCTATCGGGTCCTCACCAGTCGCAGTGAATATCGGCTCCTGCTGCGGGGCGATAACGCTGATCGACGGCTCACACCCATGGGCCGGGAGTTGGGTCTGGTGGATGATCGCCGCTGGCGCACCTTCGAGGCCAAGCAAAAGGCCATCCAGGCCCAGCAAGCCCTGTTGGAGACCACCCGCCTCAAGGCCGATGACCCGGTTAG
',
          File.read('white_rabbit.trimpoly.fa')
      end
    end

    within_construct do |construct|
      construct.directory 'alice/rabbithole' do |dir|
        dir.file 'white_rabbit.fa', input
        system 'trimpoly.rb -T white_rabbit.fa >white_rabbit.trimpoly.fa'
        assert_equal '>1|test
CAATTTGTGTGCCATCCACGCCAAGCGTGTGACGATAATGCCAAAGGATATACAACTGGCGCGAAGAATTAGGGGAGAAAGGGCATAAGCGACTAAACTTGTGTATTGTTTTTGTCATGCGTACATTTTATTTCATTTACAAAGTATTTAATAGCCTaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaattaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAA
>2|test
TCTCACGGGGCGCGGCAGGTGGGGGGGCAGCCTCCCCATGTGTTGCCCCGGGACAGCAGCTACATGGGCACCATGATTGACGATCTGGTGAGCAAGGACCTGCGGGAGCCCTATCGGGTCCTCACCAGTCGCAGTGAATATCGGCTCCTGCTGCGGGGCGATAACGCTGATCGACGGCTCACACCCATGGGCCGGGAGTTGGGTCTGGTGGATGATCGCCGCTGGCGCACCTTCGAGGCCAAGCAAAAGGCCATCCAGGCCCAGCAAGCCCTGTTGGAGACCACCCGCCTCAAGGCCGATGACCCGGTTAG
',
          File.read('white_rabbit.trimpoly.fa')
      end
    end
  end
end
