# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 

$:.unshift File.join(File.dirname(__FILE__),'..','lib')

require 'test/unit'
require 'trimpoly'
include Bio

class TrimpolyTest < Test::Unit::TestCase
  def test_foo
    # test killing the whole sequence
    sequence = 'GCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTXXXXXXXXXXXXXXXXXXXXACTTTTTTTTTTTTTTTTTTTTTTTTTTGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_both(sequence)
    assert_nil trimmed
    
    # test killing part of the sequence
    sequence = 'XXXXXXXXXXXXXTCGATTXXXXXXXXXXXXXXXXXXXXXXACAATTCGACGTCATCTACTAAGGTAGTTTTCGACGGATCCGTCTATATTCTGACGACTTTGACATCCCTTGTAACAGACATGGXXXXXXXXXXTCTAACGGCGACAAGGTTCTTCTCAGCAGTATCGGCTCTGTGGTCCGCCTCCTCGATCAGCTGCTGAGCTTTGCGGTACTTTTTTTTTTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'
    trimmed = Trimpoly.trim_both(sequence)
    assert_equal 'XXXXXXXXXXXXXTCGATTXXXXXXXXXXXXXXXXXXXXXXACAATTCGACGTCATCTACTAAGGTAGTTTTCGACGGATCCGTCTATATTCTGACGACTTTGACATCCCTTGTAACAGACATGGXXXXXXXXXXTCTAACGGCGACAAGGTTCTTCTCAGCAGTATCGGCTCTGTGGTCCGCCTCCTCGATCAGCTGCTGAGCTTTGCGGTAC', 
      trimmed
    
    # test do nothing
    sequence = 'AGGACTCTTCTGAAGACCACGTGACCCTCTGATACGGCTGAAAATATTTGATCTTCTACATTGTAATATTCTTTCAAGTGCAATATTAGTTATTTAAACTTTTATATGTTATAAAGATTCATTGTGATATTTATTGAAAATGTGAGAAAAAGAAACAATTAAATATTTTTTCTCAGGATATCGTTTCAGAATAATGCGGAGATTTCTAAAGAATAACGTTAATTCGATTGGACTGTTAAGCTCTTGTXXX'  
    trimmed = Trimpoly.trim_both(sequence)
    assert_equal sequence, trimmed
  end
end
